#!/bin/bash

echo LIBS = \\ > Libraries/.depend
for dir in $(ls -d Libraries/*)
do
    echo "    Adding simulator library - $dir"
    echo -I$dir \\ >> Libraries/.depend
done

cat Libraries/.external | sed s/\\r// | while read lib
do
    echo "    Adding external library - $lib"
    echo "-I../Libraries/$lib" \\ >> Libraries/.depend
done
echo "-I../Libraries" >> Libraries/.depend

echo "" >> Libraries/.depend
echo DEPS = \\ >> Libraries/.depend
for file in $(ls Libraries/**/*.cpp | cut -d / -f 2- | sed s/\.cpp$//)
do
    echo "    Adding simulator source - $file"
    echo "Linker/sim/$file.o" \\ >> Libraries/.depend
done

cat Libraries/.external | sed s/\\r// | while read lib
do
    for file in $(ls ../Libraries/$lib/*.cpp | cut -d / -f 3- | sed s/\.cpp$//)
    do
        echo "    Adding external source - $file"
        echo "Linker/ext/$file.o" \\ >> Libraries/.depend
    done
done