#!/bin/bash

mkdir -p ../log

if [[ -d $1 ]]; then
	indir=$1
	outdir=../log/$(basename $1)
	mkdir -p $outdir
	for infile in $(ls $indir/*.csv); do
		../build/CANParser -i $infile -o $outdir/$(basename $infile)
	done

	echo "Parsed data available at $outdir"
else
	echo $1 not a valid directory
fi