SCREEN_CONFIG_COMMON = {
    # RMS INVERTER
    'MODULE A TEMP'                  : [ 4 , 5 ],
    'MODULE B TEMP'                  : [ 5 , 5 ],
    'MODULE C TEMP'                  : [ 6 , 5 ],
    'GATE DRIVER BOARD TEMP'         : [ 7 , 5 ],
    'RTD 4 TEMP'                     : [ 8 , 5 ],
    'RTD 5 TEMP'                     : [ 9 , 5 ],
    'MOTOR TEMP'                     : [ 10 , 5 ],
    'TORQUE SHUDDER'                 : [ 11 , 5 ],
    'MOTOR ANGLE'                    : [ 12 , 5 ],
    'MOTOR SPEED'                    : [ 13 , 5 ],
    'ELEC OUTPUT FREQ'               : [ 14 , 5 ],
    'DELTA RESOLVER FILT'            : [ 15 , 5 ],
    'PHASE A CURRENT'                : [ 16 , 5 ],
    'PHASE B CURRENT'                : [ 17 , 5 ],
    'PHASE C CURRENT'                : [ 18 , 5 ],
    'DC BUS CURRENT'                 : [ 19 , 5 ],
    'DC BUS VOLTAGE'                 : [ 20 , 5 ],
    'OUTPUT VOLTAGE'                 : [ 21 , 5 ],
    'PHASE AB VOLTAGE'               : [ 22 , 5 ],
    'PHASE BC VOLTAGE'               : [ 23 , 5 ],
    'VSM STATE'                      : [ 24 , 5 ],
    'INVERTER STATE'                 : [ 25 , 5 ],
    'INVERTER RUN MODE'              : [ 26 , 5 ],
    'INVERTER ACTIVE DISCHARGE STATE': [ 27 , 5 ],
    'INVERTER COMMAND MODE'          : [ 28 , 5 ],
    'INVERTER ENABLE'                : [ 29 , 5 ],
    'INVERTER LOCKOUT'               : [ 30 , 5 ],
    'DIRECTION COMMAND'              : [ 31 , 5 ],
    'POST FAULT LO'                  : [ 32 , 5 ],
    'POST FAULT HI'                  : [ 33 , 5 ],
    'RUN FAULT LO'                   : [ 34 , 5 ],
    'RUN FAULT HI'                   : [ 35 , 5 ],
    'COMMANDED TORQUE'               : [ 36 , 5 ],
    'TORQUE FEEDBACK'                : [ 37 , 5 ],
    'RMS UPTIME'                     : [ 38 , 5 ],

    # GLV CURRENT READINGS
    'ECU CURRENT'                    : [ 41 , 5 ],
    'COOLING CURRENT'                : [ 42 , 5 ],

    # BATTERY MANAGEMENT SYSTEM
    'BMS AVERAGE TEMPERATURE'        : [ 4 , 55 ],
    'BMS LOW TEMPERATURE'            : [ 5 , 55 ],
    'BMS HIGH TEMPERATURE'           : [ 6 , 55 ],
    'BMS STATE'                      : [ 7 , 55 ],
    'BMS ERROR FLAGS'                : [ 8 , 55 ],
    'BMS CURRENT'                    : [ 9 , 55 ],
    'BMS VOLTAGE AVERAGE'            : [ 10 , 55 ],
    'BMS VOLTAGE LOW'                : [ 11 , 55 ],
    'BMS VOLTAGE HIGH'               : [ 12 , 55 ],
    'BMS VOLTAGE TOTAL'              : [ 13 , 55 ],
    'BMS TOTAL CHARGE'               : [ 14 , 55 ],
    'BMS TOTAL DISCHARGE'            : [ 15 , 55 ],

    'TCU WHEEL RPM REAR LEFT'        : [ 38 , 55 ],
    'TCU WHEEL RPM REAR RIGHT'       : [ 39 , 55 ],
    'TCU WHEEL RPM FRONT LEFT'       : [ 40 , 55 ],
    'TCU WHEEL RPM FRONT RIGHT'      : [ 41 , 55 ],

    'MCU SLIP RATIO'                 : [ 43 , 55 ],
    'MCU SLIP LIMITING FACTOR'       : [ 44 , 55 ],

    'TCU DISTANCE TRAVELED'          : [ 46 , 55 ],

    # BATTERY MANAGEMENT SYSTEM DETAILED VOLTAGES
    'IC 0 CELL 0'                    : [ 4 , 105 ],
    'IC 0 CELL 1'                    : [ 5 , 105 ],
    'IC 0 CELL 2'                    : [ 6 , 105 ],
    'IC 0 CELL 3'                    : [ 7 , 105 ],
    'IC 0 CELL 4'                    : [ 8 , 105 ],
    'IC 0 CELL 5'                    : [ 9 , 105 ],
    'IC 0 CELL 6'                    : [ 10 , 105 ],
    'IC 0 CELL 7'                    : [ 11 , 105 ],
    'IC 0 CELL 8'                    : [ 12 , 105 ],

    'IC 1 CELL 0'                    : [ 14 , 105 ],
    'IC 1 CELL 1'                    : [ 15 , 105 ],
    'IC 1 CELL 2'                    : [ 16 , 105 ],
    'IC 1 CELL 3'                    : [ 17 , 105 ],
    'IC 1 CELL 4'                    : [ 18 , 105 ],
    'IC 1 CELL 5'                    : [ 19 , 105 ],
    'IC 1 CELL 6'                    : [ 20 , 105 ],
    'IC 1 CELL 7'                    : [ 21 , 105 ],
    'IC 1 CELL 8'                    : [ 22 , 105 ],

    'IC 2 CELL 0'                    : [ 24 , 105 ],
    'IC 2 CELL 1'                    : [ 25 , 105 ],
    'IC 2 CELL 2'                    : [ 26 , 105 ],
    'IC 2 CELL 3'                    : [ 27 , 105 ],
    'IC 2 CELL 4'                    : [ 28 , 105 ],
    'IC 2 CELL 5'                    : [ 29 , 105 ],
    'IC 2 CELL 6'                    : [ 30 , 105 ],
    'IC 2 CELL 7'                    : [ 31 , 105 ],
    'IC 2 CELL 8'                    : [ 32 , 105 ],

    'IC 3 CELL 0'                    : [ 34 , 105 ],
    'IC 3 CELL 1'                    : [ 35 , 105 ],
    'IC 3 CELL 2'                    : [ 36 , 105 ],
    'IC 3 CELL 3'                    : [ 37 , 105 ],
    'IC 3 CELL 4'                    : [ 38 , 105 ],
    'IC 3 CELL 5'                    : [ 39 , 105 ],
    'IC 3 CELL 6'                    : [ 40 , 105 ],
    'IC 3 CELL 7'                    : [ 41 , 105 ],
    'IC 3 CELL 8'                    : [ 42 , 105 ],

    'IC 4 CELL 0'                    : [ 4 , 130 ],
    'IC 4 CELL 1'                    : [ 5 , 130 ],
    'IC 4 CELL 2'                    : [ 6 , 130 ],
    'IC 4 CELL 3'                    : [ 7 , 130 ],
    'IC 4 CELL 4'                    : [ 8 , 130 ],
    'IC 4 CELL 5'                    : [ 9 , 130 ],
    'IC 4 CELL 6'                    : [ 10 , 130 ],
    'IC 4 CELL 7'                    : [ 11 , 130 ],
    'IC 4 CELL 8'                    : [ 12 , 130 ],

    'IC 5 CELL 0'                    : [ 14 , 130 ],
    'IC 5 CELL 1'                    : [ 15 , 130 ],
    'IC 5 CELL 2'                    : [ 16 , 130 ],
    'IC 5 CELL 3'                    : [ 17 , 130 ],
    'IC 5 CELL 4'                    : [ 18 , 130 ],
    'IC 5 CELL 5'                    : [ 19 , 130 ],
    'IC 5 CELL 6'                    : [ 20 , 130 ],
    'IC 5 CELL 7'                    : [ 21 , 130 ],
    'IC 5 CELL 8'                    : [ 22 , 130 ],

    'IC 6 CELL 0'                    : [ 24 , 130 ],
    'IC 6 CELL 1'                    : [ 25 , 130 ],
    'IC 6 CELL 2'                    : [ 26 , 130 ],
    'IC 6 CELL 3'                    : [ 27 , 130 ],
    'IC 6 CELL 4'                    : [ 28 , 130 ],
    'IC 6 CELL 5'                    : [ 29 , 130 ],
    'IC 6 CELL 6'                    : [ 30 , 130 ],
    'IC 6 CELL 7'                    : [ 31 , 130 ],
    'IC 6 CELL 8'                    : [ 32 , 130 ],

    'IC 7 CELL 0'                    : [ 34 , 130 ],
    'IC 7 CELL 1'                    : [ 35 , 130 ],
    'IC 7 CELL 2'                    : [ 36 , 130 ],
    'IC 7 CELL 3'                    : [ 37 , 130 ],
    'IC 7 CELL 4'                    : [ 38 , 130 ],
    'IC 7 CELL 5'                    : [ 39 , 130 ],
    'IC 7 CELL 6'                    : [ 40 , 130 ],
    'IC 7 CELL 7'                    : [ 41 , 130 ],
    'IC 7 CELL 8'                    : [ 42 , 130 ],

    # BATTERY MANAGEMENT SYSTEM DETAILED TEMPERATURES
    'IC 0 THERM 0'                   : [ 4 , 155 ],
    'IC 0 THERM 1'                   : [ 5 , 155 ],
    'IC 0 THERM 2'                   : [ 6 , 155 ],

    'IC 1 THERM 0'                   : [ 8 , 155 ],
    'IC 1 THERM 1'                   : [ 9 , 155 ],
    'IC 1 THERM 2'                   : [ 10 , 155 ],

    'IC 2 THERM 0'                   : [ 12 , 155 ],
    'IC 2 THERM 1'                   : [ 13 , 155 ],
    'IC 2 THERM 2'                   : [ 14 , 155 ],

    'IC 3 THERM 0'                   : [ 16 , 155 ],
    'IC 3 THERM 1'                   : [ 17 , 155 ],
    'IC 3 THERM 2'                   : [ 18 , 155 ],

    'IC 4 THERM 0'                   : [ 4 , 180 ],
    'IC 4 THERM 1'                   : [ 5 , 180 ],
    'IC 4 THERM 2'                   : [ 6 , 180 ],

    'IC 5 THERM 0'                   : [ 8 , 180 ],
    'IC 5 THERM 1'                   : [ 9 , 180 ],
    'IC 5 THERM 2'                   : [ 10 , 180 ],

    'IC 6 THERM 0'                   : [ 12 , 180 ],
    'IC 6 THERM 1'                   : [ 13 , 180 ],
    'IC 6 THERM 2'                   : [ 14 , 180 ],

    'IC 7 THERM 0'                   : [ 16 , 180 ],
    'IC 7 THERM 1'                   : [ 17 , 180 ],
    'IC 7 THERM 2'                   : [ 18 , 180 ]
}

SCREEN_CONFIG_FCU = {
    'FCU UPTIME'        : [ 18 , 55 ],
    'FCU STATE'         : [ 19 , 55 ],
    'START BUTTON ID'   : [ 20 , 55 ],
    'FCU RAW TORQUE'    : [ 21 , 55 ],
    'REQUESTED TORQUE'  : [ 22 , 55 ],

    'FCU PEDAL ACCEL 1' : [ 23 , 55 ],
    'FCU PEDAL ACCEL 2' : [ 24 , 55 ],
    'FCU PEDAL BRAKE'   : [ 25 , 55 ],
    'FCU BRAKE ACT'     : [ 26 , 55 ],
    'FCU IMPLAUS ACCEL' : [ 27 , 55 ],
    'FCU IMPLAUS BRAKE' : [ 28 , 55 ],

    # REAR CONTROL UNIT
    'RCU UPTIME'        : [ 31 , 55 ],
    'RCU STATE'         : [ 32 , 55 ],
    'RCU FLAGS'         : [ 33 , 55 ],
    'GLV BATT VOLTAGE'  : [ 34 , 55 ],
    'RCU BMS FAULT'     : [ 35 , 55 ],
    'RCU IMD FAULT'     : [ 36 , 55 ]
}

# MAIN CONTROL UNIT
SCREEN_CONFIG_MCU = {
  'MCU STATE'                 : [ 18 , 55 ],
  'MCU BMS FAULT'             : [ 19 , 55 ],
  'MCU IMD FAULT'             : [ 20 , 55 ],
  'MCU INVERTER POWER'        : [ 21 , 55 ],
  'MCU SHUTDOWN ABOVE THRESH' : [ 22 , 55 ],
  'MCU TEMPERATURE'           : [ 23 , 55 ],
  'MCU GLV VOLTAGE'           : [ 24 , 55 ],
  'MCU PEDAL ACCEL 1'         : [ 25 , 55 ],
  'MCU PEDAL ACCEL 2'         : [ 26 , 55 ],
  'MCU PEDAL BRAKE'           : [ 27 , 55 ],
  'MCU BRAKE ACT'             : [ 28 , 55 ],
  'MCU IMPLAUS ACCEL'         : [ 29 , 55 ],
  'MCU IMPLAUS BRAKE'         : [ 30 , 55 ],
  'MCU TORQUE MAP MODE'       : [ 31 , 55 ],
  'REQUESTED TORQUE'          : [ 32 , 55 ]
}

def get_config(type):
    return { **(SCREEN_CONFIG_FCU if type == "fcu" else SCREEN_CONFIG_MCU), **SCREEN_CONFIG_COMMON }
