CONSOLE_CONFIG = {
    # RMS INVERTER
    'MODULE A TEMPERATURE'           : [ 4 , 5 ],
    'MODULE B TEMPERATURE'           : [ 5 , 5 ],
    'MODULE C TEMPERATURE'           : [ 6 , 5 ],
    'GATE DRIVER BOARD TEMPERATURE'  : [ 7 , 5 ],
    'RTD 4 TEMPERATURE'              : [ 8 , 5 ],
    'RTD 5 TEMPERATURE'              : [ 9 , 5 ],
    'MOTOR TEMPERATURE'              : [ 10 , 5 ],
    'TORQUE SHUDDER'                 : [ 11 , 5 ],
    'MOTOR ANGLE'                    : [ 12 , 5 ],
    'MOTOR SPEED'                    : [ 13 , 5 ],
    'ELEC OUTPUT FREQ'               : [ 14 , 5 ],
    'DELTA RESOLVER FILTERED'        : [ 15 , 5 ],
    'PHASE A CURRENT'                : [ 16 , 5 ],
    'PHASE B CURRENT'                : [ 17 , 5 ],
    'PHASE C CURRENT'                : [ 18 , 5 ],
    'DC BUS CURRENT'                 : [ 19 , 5 ],
    'DC BUS VOLTAGE'                 : [ 20 , 5 ],
    'OUTPUT VOLTAGE'                 : [ 21 , 5 ],
    'PHASE AB VOLTAGE'               : [ 22 , 5 ],
    'PHASE BC VOLTAGE'               : [ 23 , 5 ],
    'VSM STATE'                      : [ 24 , 5 ],
    'INVERTER STATE'                 : [ 25 , 5 ],
    'INVERTER RUN MODE'              : [ 26 , 5 ],
    'INVERTER ACTIVE DISCHARGE STATE': [ 27 , 5 ],
    'INVERTER COMMAND MODE'          : [ 28 , 5 ],
    'INVERTER ENABLE STATE'          : [ 29 , 5 ],
    'INVERTER ENABLE LOCKOUT'        : [ 30 , 5 ],
    'DIRECTION COMMAND'              : [ 31 , 5 ],
    'POST FAULT LO'                  : [ 32 , 5 ],
    'POST FAULT HI'                  : [ 33 , 5 ],
    'RUN FAULT LO'                   : [ 34 , 5 ],
    'RUN FAULT HI'                   : [ 35 , 5 ],
    'COMMANDED TORQUE'               : [ 36 , 5 ],
    'TORQUE FEEDBACK'                : [ 37 , 5 ],
    'RMS UPTIME'                     : [ 38 , 5 ],

    # MCU ANALOG READINGS
    'ECU CURRENT'                    : [ 41 , 5 ],
    'COOLING CURRENT'                : [ 42 , 5 ],
    'TEMPERATURE'                    : [ 43,  5 ],
    'GLV BATTERY VOLTAGE'            : [ 44,  5 ],

    # DASHBOARD STATUS
    'SSOK ABOVE THRESHOLD'           : [ 47,  5 ],
    'SHUTDOWN H ABOVE THRESHOLD'     : [ 48,  5 ],

    # BATTERY MANAGEMENT SYSTEM
    'BMS AVERAGE TEMPERATURE'        : [ 4 , 55 ],
    'BMS LOW TEMPERATURE'            : [ 5 , 55 ],
    'BMS HIGH TEMPERATURE'           : [ 6 , 55 ],
    'BMS STATE'                      : [ 7 , 55 ],
    'BMS ERROR FLAGS'                : [ 8 , 55 ],
    'BMS CURRENT'                    : [ 9 , 55 ],
    'BMS VOLTAGE AVERAGE'            : [ 10 , 55 ],
    'BMS VOLTAGE LOW'                : [ 11 , 55 ],
    'BMS VOLTAGE HIGH'               : [ 12 , 55 ],
    'BMS VOLTAGE TOTAL'              : [ 13 , 55 ],
    'BMS TOTAL CHARGE'               : [ 14 , 55 ],
    'BMS TOTAL DISCHARGE'            : [ 15 , 55 ],

	# MAIN CONTROL UNIT
	'IMD OK HIGH'                 	 : [ 18 , 55 ],
	'BMS OK HIGH'             	     : [ 19 , 55 ],
	'BSPD OK HIGH'             	     : [ 20 , 55 ],
	'SOFTWARE OK HIGH'        	     : [ 21 , 55 ],
	'SHUTDOWN D ABOVE THRESHOLD' 	 : [ 22 , 55 ],
	'SHUTDOWN E ABOVE THRESHOLD'     : [ 23 , 55 ],
	'INVERTER POWERED'           	 : [ 24 , 55 ],
	'ACCELERATOR PEDAL 1'         	 : [ 25 , 55 ],
	'ACCELERATOR PEDAL 2'         	 : [ 26 , 55 ],
	'BRAKE TRANSDUCER 1'           	 : [ 27 , 55 ],
    'BRAKE TRANSDUCER 2'             : [ 28 , 55 ],
	'BRAKE PEDAL ACTIVE'             : [ 29 , 55 ],
	'NO ACCEL IMPLAUSIBILITY'        : [ 30 , 55 ],
	'NO BRAKE IMPLAUSIBILITY'        : [ 31 , 55 ],
	'TORQUE MODE'       	         : [ 32 , 55 ],
    'MAX TORQUE'                     : [ 33,  55 ],
	'REQUESTED TORQUE'          	 : [ 34 , 55 ],

    'RPM BACK LEFT'                  : [ 38 , 55 ],
    'RPM BACK RIGHT'                 : [ 39 , 55 ],
    'RPM FRONT LEFT'                 : [ 40 , 55 ],
    'RPM FRONT RIGHT'                : [ 41 , 55 ],

    # BATTERY MANAGEMENT SYSTEM DETAILED VOLTAGES
    'IC 0 CELL 0'                    : [ 4 , 105 ],
    'IC 0 CELL 1'                    : [ 5 , 105 ],
    'IC 0 CELL 2'                    : [ 6 , 105 ],
    'IC 0 CELL 3'                    : [ 7 , 105 ],
    'IC 0 CELL 4'                    : [ 8 , 105 ],
    'IC 0 CELL 5'                    : [ 9 , 105 ],
    'IC 0 CELL 6'                    : [ 10 , 105 ],
    'IC 0 CELL 7'                    : [ 11 , 105 ],
    'IC 0 CELL 8'                    : [ 12 , 105 ],

    'IC 1 CELL 0'                    : [ 14 , 105 ],
    'IC 1 CELL 1'                    : [ 15 , 105 ],
    'IC 1 CELL 2'                    : [ 16 , 105 ],
    'IC 1 CELL 3'                    : [ 17 , 105 ],
    'IC 1 CELL 4'                    : [ 18 , 105 ],
    'IC 1 CELL 5'                    : [ 19 , 105 ],
    'IC 1 CELL 6'                    : [ 20 , 105 ],
    'IC 1 CELL 7'                    : [ 21 , 105 ],
    'IC 1 CELL 8'                    : [ 22 , 105 ],

    'IC 2 CELL 0'                    : [ 24 , 105 ],
    'IC 2 CELL 1'                    : [ 25 , 105 ],
    'IC 2 CELL 2'                    : [ 26 , 105 ],
    'IC 2 CELL 3'                    : [ 27 , 105 ],
    'IC 2 CELL 4'                    : [ 28 , 105 ],
    'IC 2 CELL 5'                    : [ 29 , 105 ],
    'IC 2 CELL 6'                    : [ 30 , 105 ],
    'IC 2 CELL 7'                    : [ 31 , 105 ],
    'IC 2 CELL 8'                    : [ 32 , 105 ],

    'IC 3 CELL 0'                    : [ 34 , 105 ],
    'IC 3 CELL 1'                    : [ 35 , 105 ],
    'IC 3 CELL 2'                    : [ 36 , 105 ],
    'IC 3 CELL 3'                    : [ 37 , 105 ],
    'IC 3 CELL 4'                    : [ 38 , 105 ],
    'IC 3 CELL 5'                    : [ 39 , 105 ],
    'IC 3 CELL 6'                    : [ 40 , 105 ],
    'IC 3 CELL 7'                    : [ 41 , 105 ],
    'IC 3 CELL 8'                    : [ 42 , 105 ],

    'IC 4 CELL 0'                    : [ 4 , 130 ],
    'IC 4 CELL 1'                    : [ 5 , 130 ],
    'IC 4 CELL 2'                    : [ 6 , 130 ],
    'IC 4 CELL 3'                    : [ 7 , 130 ],
    'IC 4 CELL 4'                    : [ 8 , 130 ],
    'IC 4 CELL 5'                    : [ 9 , 130 ],
    'IC 4 CELL 6'                    : [ 10 , 130 ],
    'IC 4 CELL 7'                    : [ 11 , 130 ],
    'IC 4 CELL 8'                    : [ 12 , 130 ],

    'IC 5 CELL 0'                    : [ 14 , 130 ],
    'IC 5 CELL 1'                    : [ 15 , 130 ],
    'IC 5 CELL 2'                    : [ 16 , 130 ],
    'IC 5 CELL 3'                    : [ 17 , 130 ],
    'IC 5 CELL 4'                    : [ 18 , 130 ],
    'IC 5 CELL 5'                    : [ 19 , 130 ],
    'IC 5 CELL 6'                    : [ 20 , 130 ],
    'IC 5 CELL 7'                    : [ 21 , 130 ],
    'IC 5 CELL 8'                    : [ 22 , 130 ],

    'IC 6 CELL 0'                    : [ 24 , 130 ],
    'IC 6 CELL 1'                    : [ 25 , 130 ],
    'IC 6 CELL 2'                    : [ 26 , 130 ],
    'IC 6 CELL 3'                    : [ 27 , 130 ],
    'IC 6 CELL 4'                    : [ 28 , 130 ],
    'IC 6 CELL 5'                    : [ 29 , 130 ],
    'IC 6 CELL 6'                    : [ 30 , 130 ],
    'IC 6 CELL 7'                    : [ 31 , 130 ],
    'IC 6 CELL 8'                    : [ 32 , 130 ],

    'IC 7 CELL 0'                    : [ 34 , 130 ],
    'IC 7 CELL 1'                    : [ 35 , 130 ],
    'IC 7 CELL 2'                    : [ 36 , 130 ],
    'IC 7 CELL 3'                    : [ 37 , 130 ],
    'IC 7 CELL 4'                    : [ 38 , 130 ],
    'IC 7 CELL 5'                    : [ 39 , 130 ],
    'IC 7 CELL 6'                    : [ 40 , 130 ],
    'IC 7 CELL 7'                    : [ 41 , 130 ],
    'IC 7 CELL 8'                    : [ 42 , 130 ],

    # BATTERY MANAGEMENT SYSTEM DETAILED TEMPERATURES
    'IC 0 THERM 0'                   : [ 4 , 155 ],
    'IC 0 THERM 1'                   : [ 5 , 155 ],
    'IC 0 THERM 2'                   : [ 6 , 155 ],

    'IC 1 THERM 0'                   : [ 8 , 155 ],
    'IC 1 THERM 1'                   : [ 9 , 155 ],
    'IC 1 THERM 2'                   : [ 10 , 155 ],

    'IC 2 THERM 0'                   : [ 12 , 155 ],
    'IC 2 THERM 1'                   : [ 13 , 155 ],
    'IC 2 THERM 2'                   : [ 14 , 155 ],

    'IC 3 THERM 0'                   : [ 16 , 155 ],
    'IC 3 THERM 1'                   : [ 17 , 155 ],
    'IC 3 THERM 2'                   : [ 18 , 155 ],

    'IC 4 THERM 0'                   : [ 4 , 180 ],
    'IC 4 THERM 1'                   : [ 5 , 180 ],
    'IC 4 THERM 2'                   : [ 6 , 180 ],

    'IC 5 THERM 0'                   : [ 8 , 180 ],
    'IC 5 THERM 1'                   : [ 9 , 180 ],
    'IC 5 THERM 2'                   : [ 10 , 180 ],

    'IC 6 THERM 0'                   : [ 12 , 180 ],
    'IC 6 THERM 1'                   : [ 13 , 180 ],
    'IC 6 THERM 2'                   : [ 14 , 180 ],

    'IC 7 THERM 0'                   : [ 16 , 180 ],
    'IC 7 THERM 1'                   : [ 17 , 180 ],
    'IC 7 THERM 2'                   : [ 18 , 180 ]
}
